from diff_tree import DiffTree


def test(expression, var):
    print("Исходное выражение: " + expression)
    tree = DiffTree("operations.txt")
    try:
        tree.from_str(expression)
        print("Дерево: " + str(tree))
        print("Производная по " + var + ": " + str(tree.diff(var)))

    except Exception as e:
        print(e)

    print("\n")


test("(((x)))", "x")
test("x", "b")
test("-x", "x")
test("12.5", "x")
test("-33.66", "x")
test("sin(a*x)", "x")
test("cos(x + 10)", "x")
test("tg(3*x)", "x")
test("ctg(x + 25.3)", "x")
test("arcsin(10.7*x)", "x")
test("arccos(x*a)", "a")
test("arctg(x - -b)", "x")
test("arcctg(x + -b)", "x")
test("sh(-a*x)", "x")
test("ch(a*x)", "x")
test("th(-a*x)", "x")
test("cth(a*x)", "x")
test("sqrt(x + (b - c))", "x")
test("sin(a*x)", "c")
test("(a*x)^3", "x")
test("5^(x + 3)", "x")
test("e^-x", "x")
test("a^1200", "x")
test("x^x", "x")
test("ln(150.36)", "x")
test("ln(-2*x)", "x")
test("log(a*b*c, d*e*f)", "x")
test("log(2, x + c)", "x")
test("log(a*x, 5)", "x")
test("log(2*x, a*x)", "x")
test("a*x + b*x", "x")
test("2.5 + a*x", "x")
test("2 + a + b", "x")
test("2*x - a*x", "x")
test("2.5 - a*x", "x")
test("2 - a - b", "x")
test("a*b", "x")
test("a*x", "x")
test("x*b", "x")
test("x*x", "x")
test("a/b", "x")
test("a/x", "x")
test("x/b", "x")
test("x/x", "x")
test("2++3", "x")
test("sin + 3", "x")
test("3-", "x")
test("log(x)", "x")
test("sin(x, y)", "x")
test("25 + a 6", "x")
test("2(a+b)", "x")
test("35.5, b*6", "x")
test("()", "x")
test("(a+b", "x")
